# test.type = 'error'
#
# [test.metadata]
# error = 'EvalError::BlameError'
let f : Number -> Number = fun x => x in
f "a"
